version: '3'
services:
  mysqldb:
    build: ./database/mysql
    env_file:
      - ./database/mysql.env
    container_name: db_mysql
    environment:
      - TZ=Asia/Seoul
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    ports:
      - '3306:3306'
      - '33060:33060'
    volumes:
      - ../database/mysql/res/data:/var/lib/mysql
    command: "mysqld"
