FROM python:3.9
WORKDIR /crow
RUN pip install selenium webdriver_manager pymysql
RUN curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
RUN apt-get update && apt-get install -y google-chrome-stable
CMD ["python", "getStartBlind.py"]