spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 1d00d14f1ffe2865a5b8a876c3de14da
            redirect-uri: http://localhost:3000/oauth/kakao
            client-authentication-method: POST
            client-secret: RuSnmrJFbGlDMMV4IO8dEbSzFlPSLSHK
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
              - account_email
              - gender
              - birthday
            client_name: kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  token:
    secret-key: jobtender
  access-token:
    expire-length: 1800000
  refresh-token:
    expire-length: 1209600000